CREATE PROC FI_SP_IncBenefi
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (11),
	  @IDCLIENTE          bigint  
AS
BEGIN
	INSERT INTO BENEFICIARIOS(NOME, CPF, IDCLIENTE  ) 
	VALUES (@NOME, @CPF, @IDCLIENTE )

	SELECT SCOPE_IDENTITY()
END